### ISSUE TITLE
USER STORY: Anonymous poll feedback

### ISSUE THREAD

**Issue by aimansae** [aimansae/My-First-User-Story#4]
As a **user** I can **provide my feedback anonymously** so that **I can** decide to hide my identity

**Comment by aimansae** [comment]
## Acceptance Criteria

1. The option should be provided as a checkbox
2. The checkbox should be “checked” by default
3. The option should appear next to the submit button
4. After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks

- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update controller function
- [ ] Update unit tests scripts
- [ ] Test the funcionality
